services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            platforms:
                - linux/amd64
                - linux/arm64
        image: ghcr.io/zebra-pro-dev/laravel-base:latest
